### ISSUE TITLE
Add support for CowString

### ISSUE THREAD

**Issue by freebroccolo** [epsilonz/pretty.rs#25]
See [here](http://doc.rust-lang.org/std/string/type.CowString.html) and [here](http://doc.rust-lang.org/std/borrow/enum.Cow.html). In particular, it shouldn't be necessary to `clone` string data from a structure to put it into a `Doc` in all cases.

**Comment by freebroccolo** [comment]
Looks like this shaved another ~1000ns off the benchmarks too.

**Comment by jonsterling** [comment]
Heh, nice...

**Comment by freebroccolo** [comment]
Yeah, I'm seeing it down to around 5500ns or so, pretty sweet :]
